# Generated by Django 3.2.12 on 2024-02-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_contraseñas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestor',
            old_name='usuario',
            new_name='dni',
        ),
    ]
